import { LocalImageType, RemoteImageType } from "../contexts/clientorContext";
import { LinkDataType } from "../functionalities/insertLinks";
import { isLocalImage } from "../types/types";
import { getImageIDFromDOM, getImageURL } from "./getters";

export const formatLink = (linkData: LinkDataType) => {
  return {
    mdx: `[${linkData.label || linkData.link}](${linkData.link})`,
    rtx: () => {
      let attributes = `href="${linkData.link}"`;
      if (linkData.target) {
        attributes += ` target="_${linkData.target}"`;
      }
      let linkText = `<a ${attributes}>${linkData.label || linkData.link}</a>`;
      return linkText;
    },
  };
};

export const formatImage = (image: LocalImageType | RemoteImageType) => {
  let label = `Preview image ${image.id}`;

  const mdx = isLocalImage(image)
    ? `![${label}](${getImageURL(image.file)})`
    : `![${label}](${image.url})`;

  const rtx = () => {
    return isLocalImage(image)
      ? `<img src="${getImageURL(
          image.file
        )}" alt="${label}" class="clientor-inserted-image-${image.id}">` // Tags should not be self encoded
      : `<img src="${image.url}" alt="${label}" class="clientor-inserted-image-${image.id}">`; // Tags should not be self encoded
  };

  /*

    1. 
      All the images have a 'clientor-inserted-image-{id}' classname
      so they can be easily targeted and remove.

    2. 
      Tags should not be self closed because to remove an image element from the htmlText state
      we first select it, take its outerHTML and replace any substring that matches the outerHTML by an empty string.
      In the DOM, the closing tag gets removed. So, if in the state the closed tag exists but not in the string
      gotten from outerHTML of the DOM element, the strings won't match.

      So, please, no matter what, never self close the orphan tags.


  */

  return {
    mdx,
    rtx,
    id: image.id,
  };
};

const blobImagePattern = /^blob/;
export const formatFinalHtml = (element: HTMLDivElement) => {
  const images = element.querySelectorAll("img");

  for (let image of images) {
    /*
      Only replace the blob urls. If that's not the case,
      skip the current image.

      We only want to replace the src of the images elements
      that hold local images urls generated by URL.createObjectURL(file)
    */
    if (!blobImagePattern.test(image.src)) {
      continue;
    }

    let id = getImageIDFromDOM(image);

    if (!id) {
      continue;
    }

    /*
      Replace the Blob URL by the id of the image
      so the user can replace the src by the real
      URL of the image later on.
    */
    image.src = id;
  }

  return element.innerHTML;
};
